spring:
  application:
    name: discodeit # 애플리케이션 이름 -> discodeit

  profiles:
    active: dev # 기본 프로파일

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나의 최대 크기
      max-request-size: 20MB # 한 번에 최대 업로드 가능 용량

  jpa:
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 정렬
        highlight_sql: true # 콘솔 로그에 색상
        use_sql_comments: true # 쿼리에 주석을 추가
    open-in-view: false # OSIV 비활성화 -> Service 계층에서 DTO로 변환해서 Controller 계층으로 넘길 것

  # 사용이유 1 - JPA가 자동으로 생성해주는 DDL은 ON DELETE SET NULL 같은 상세한 DB 제약 조건을 완벽하게 생성하지 못하는 경우가 많다.
  # 사용이유 2 - ddl-auto는 코드에 따라 실시간으로 변하므로 git을 통해 이력 관리가 어렵다
  # ddl-auto가 생성한 SQL 코드는 기본적으로 파일 형태로 남지 않고 메모리상에서 실행된후 사라진다.
  sql:
    init:
      mode: always # always: 사용하는 DB 종류와 상관없이, 서버가 시작될 때마다 항상 스크립트를 실행
      schema-locations: classpath:schema.sql # 실행할 스키마(테이블 구조 등) SQL 파일의 경로를 지정
      # classpath: 프로젝트의 리소스 폴더(src/main/resources)를 의미

# === Swagger-UI 설정 ===
springdoc:
  api-docs:
    enabled: true # OpenAPI 명세 자동 생성 기능 활성화 -> http://localhost:8080/v3/api-docs
  swagger-ui:
    enabled: true # Swagger UI 웹 화면을 활성화 -> http://localhost:8080/swagger-ui/index.html
  default-produces-media-type: application/json # API 문서에서 기본 응답 콘텐츠 타입을 application/json으로 간주하도록 설정

# === 로깅 설정 ===
logging:
  level:
    root: info # 전체 기본 로깅 레벨
    org.hibernate.SQL: debug # Hibernate가 실행하는 SQL 쿼리문 자체를 로그로 출력
    org.hibernate.orm.jdbc.bind: trace # 쿼리 파라미터에 바인딩되는 값을 확인하기 위한 설정

discodeit:
  storage:
    type: local
    # 설정값(local)과 어노테이션에 지정된 havingValue가 일치하므로 LocalBinaryContentStorage는 스프링 빈으로 등록됨
    local:
      root-path: .discodeit/storage
      # @Value("${discodeit.storage.local.root-path}") 를 통해서 할당됨

# === Actuator 설정 ===
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers # 노출할 엔드포인트 목록
        # health: 서버 정상 여부, DB 연결 여부
        # info: 앱 버전, 빌드 정보, 커스텀 정보
        # metrics: JVM 메모리, HTTP 요청 수, CPU, GC 등 지표
        # loggers: 로거 레벨 조회/변경
  endpoint:
    health:
      show-details: always # 상세 health 정보 표시 (DB, 디스크 등)
  info:
    env:
      enabled: true # info.* 설정값을 /actuator/info에 노출

# === /actuator/info 노출 정보 ===
info:
  app:
    name: Discodeit # 애플리케이션 이름
    version: 1.7.0 # 애플리케이션 버전
  java:
    version: 17 # 자바 버전
  spring-boot:
    version: 3.4.0 # 스프링 부트 버전
  # 주요 설정 정보
  config:
    datasource:
      url: ${DB_URL}
      driver-class-name: org.postgresql.Driver
    jpa:
      ddl-auto: none # 아무 작업 안함 / 실제 설정에서는 ddl-auto로 설정 안 해 놓음
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}