spring:
  application:
    name: discodeit
  server:
    port: 8080

  ## Swagger-UI 설정
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
    default-produces-media-type: application/json

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # schema.sql을 통해 테이블을 직접 생성하므로,
      # 애플리케이션 실행 시 DB 구조가 일치하는지 검증만 수행
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 정렬
        highlight_sql: true # 콘솔 로그에 색상
        use_sql_comments: true # 쿼리에 주석을 추가
    # 심화 요구사항: 성능과 명확한 트랜잭션 경계를 위해 OSIV를 비활성화
    open-in-view: false

logging:
  level:
    # 쿼리 파라미터(PreparedStatement)에 바인딩되는 값을 확인하기 위한 설정
    org.hibernate.orm.jdbc.bind: trace

discodeit:
  storage:
    type: local
    # 설정값(local)과 어노테이션에 지정된 havingValue가 일치하므로 LocalBinaryContentStorage는 스프링 빈으로 등록됨
    local:
      root-path: .discodeit/storage
      # @Value("${discodeit.storage.local.root-path}") 를 통해서 할당됨