spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver # H2 전용 드라이버 클래스
    username: sa # H2 기본 관리자 계정 (System Admin)
    password: # 비밀번호 없음
  jpa:
    hibernate:
      ddl-auto: none # Hibernate가 엔티티 클래스를 보고 자동으로 테이블을 생성/수정하지 않음
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/test-storage

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.sprint.mission.discodeit: DEBUG

# jdbc: jdbc 프로토콜
# h2: H2 데이터베이스
# mem: 인메모리
# testdb: 데이터베이스 이름
# MODE=PostgreSQL: PostgreSQL 호환 모드 활성화
# DATABASE_TO_LOWER=TRUE: 테이블/컬럼명을 소문자로 변환
# DEFAULT_NULL_ORDERING=HIGH: NULL 정렬 순서를 PostgreSQL과 동일하게