spring:
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  profiles:
    active:
      - dev
  config:
    import: optional:file:.env[.properties]
  cache:
    type: caffeine # Srping Cache의 구현체로 Caffeine을 사용
    cache-names: users, userChannels, userNotifications # 사용한 캐시 이름 목록
    caffeine:
      # 캐시에 저장할 수 있는 최대 항목 수, 마지막 접근으로부터 600초 후 반료, 캐시 통계 수집 활성화
      spec: maximumSize=100, expireAfterAccess=600s, recordStats
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # 메시지 키를 직렬화할 클래스
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 메시지 값(payload)을 직렬화할 클래스
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 이 Consumer가 속할 Consumer Group ID
      # 같은 group-id를 가진 Consumer끼리 파티션을 나눠서 병렬 소비
      # 서로 다른 group-id면 동일 토픽 메시지를 독립적으로 각자 소비
      group-id: discodeit-group
      # Consumer Group이 처음 생성되었거나 offset 정보가 없을 때 어느 위치부터 읽을지 결정
      # earliest -> 토픽의 가장 첫 번째 메시지부터 읽음 (메시지 유실 방지에 유리)
      # latest   -> 이 Consumer가 구독을 시작한 시점 이후의 새 메시지만 읽음
      auto-offset-reset: earliest
      # 메시지 키를 역직렬화할 클래스
      # Producer의 key-serializer와 반드시 대칭 구조여야 함
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 메시지 값(payload)을 역직렬화할 클래스
      # Producer의 value-serializer와 반드시 대칭 구조여야 함
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,caches,prometheus
  endpoint:
    health:
      show-details: always
  observations:
    annotations:
      enabled: true

info:
  name: Discodeit
  version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.maxFileSize}
      max-request-size: ${spring.servlet.multipart.maxRequestSize}

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
  admin:
    username: ${DISCODEIT_ADMIN_USERNAME:admin}
    email: ${DISCODEIT_ADMIN_EMAIL:admin@discodeit.com}
    password: ${DISCODEIT_ADMIN_PASSWORD:admin1234}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiry: 1800000 # 30 minutes (ms)
    refresh-token-expiry: 1209600000 # 14 days (ms)
    max-active-count: 1 # 최대 동시 로그인 수

logging:
  level:
    root: info
